### ISSUE TITLE
Container image isn't compatible with arm64

### ISSUE THREAD

**Issue by jeremiahsnapp** [kubebeam/trivy-headlamp-plugin#10]
Thanks for the great plugin! I tried using the [example headlamp helm values](https://github.com/kubebeam/trivy-headlamp-plugin/blob/main/examples/headlamp-helm-values.yaml) to create an init container to install the plugin but I run Headlamp on arm64 systems. The ghcr.io/kubebeam/trivy-headlamp-plugin:latest container image is built for amd64 so it couldn't start.  Can you build the trivy-headlamp-plugin image for arm64?

In the meantime I'm using the following workaround to install it.

```
config:
  pluginsDir: /build/plugins

initContainers:
  - command:
      - /bin/sh
      - -c
      - |
        curl -LO https://github.com/kubebeam/trivy-headlamp-plugin/releases/download/v0.2.0/trivy-headlamp-plugin-v0.2.0.tar.gz
        tar -xvf trivy-headlamp-plugin-v0.2.0.tar.gz
        rm trivy-headlamp-plugin-v0.2.0.tar.gz
        mv trivy-plugin /build/plugins/
    image: curlimages/curl:latest
    name: trivy-plugin
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins

volumeMounts:
  - name: headlamp-plugins
    mountPath: /build/plugins

volumes:
  - name: headlamp-plugins
    emptyDir: {}
```
